name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Still triggers on main branch for "latest" image
    tags:
      - '*'  # Triggers on any tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Determine the Docker tag (use "latest" for main branch; tag name for tag pushes)
      - name: Set Docker tag
        id: docker_tag
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
          else
            echo "tag=latest" >> $GITHUB_ENV
          fi

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hbcd_qmri_postproc:${{ env.tag }} .

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hbcd_qmri_postproc:${{ env.tag }}